export default [
  {
    id: "Q",
    padName: "Q",
    audioClipName: "Chord-1",
    keyTrigger: "Q",
    keyCode: 81,
    audioClipUrl: "https://s3.amazonaws.com/freecodecamp/drums/Chord_1.mp3",
  },
  {
    id: "W",
    padName: "W",
    audioClipName: "Chord-2",
    keyTrigger: "W",
    keyCode: 87,
    audioClipUrl: "https://s3.amazonaws.com/freecodecamp/drums/Chord_2.mp3",
  },
  {
    id: "E",
    padName: "E",
    audioClipName: "Chord-3",
    keyTrigger: "E",
    keyCode: 69,
    audioClipUrl: "https://s3.amazonaws.com/freecodecamp/drums/Chord_3.mp3",
  },
  {
    id: "A",
    padName: "A",
    audioClipName: "Give us a Light",
    keyTrigger: "A",
    keyCode: 65,
    audioClipUrl:
      "https://s3.amazonaws.com/freecodecamp/drums/Give_us_a_light.mp3",
  },
  {
    id: "S",
    padName: "S",
    audioClipName: "Dry Ohh",
    keyTrigger: "S",
    keyCode: 83,
    audioClipUrl: "https://s3.amazonaws.com/freecodecamp/drums/Dry_Ohh.mp3",
  },
  {
    id: "D",
    padName: "D",
    audioClipName: "Heater-1",
    keyTrigger: "D",
    keyCode: 68,
    audioClipUrl: "https://s3.amazonaws.com/freecodecamp/drums/Bld_H1.mp3",
  },
  {
    id: "Z",
    padName: "Z",
    audioClipName: "Kick 1",
    keyTrigger: "Z",
    keyCode: 90,
    audioClipUrl:
      "https://s3.amazonaws.com/freecodecamp/drums/punchy_kick_1.mp3",
  },
  {
    id: "X",
    padName: "X",
    audioClipName: "Side Stick 1",
    keyTrigger: "X",
    keyCode: 88,
    audioClipUrl:
      "https://s3.amazonaws.com/freecodecamp/drums/side_stick_1.mp3",
  },
  {
    id: "C",
    padName: "C",
    audioClipName: "Snare",
    keyTrigger: "C",
    keyCode: 67,
    audioClipUrl: "https://s3.amazonaws.com/freecodecamp/drums/Brk_Snr.mp3",
  },
];
