export default [
  {
    id: "Q",
    name: "Chord-1",
    keyTrigger: "Q",
    keyCode: 81,
    url: "https://s3.amazonaws.com/freecodecamp/drums/Chord_1.mp3",
  },
  {
    id: "W",
    name: "Chord-2",
    keyTrigger: "W",
    keyCode: 87,
    url: "https://s3.amazonaws.com/freecodecamp/drums/Chord_2.mp3",
  },
  {
    id: "E",
    name: "Chord-3",
    keyTrigger: "E",
    keyCode: 69,
    url: "https://s3.amazonaws.com/freecodecamp/drums/Chord_3.mp3",
  },
  {
    id: "A",
    name: "Give us a Light",
    keyTrigger: "A",
    keyCode: 65,
    url: "https://s3.amazonaws.com/freecodecamp/drums/Give_us_a_light.mp3",
  },
  {
    id: "S",
    name: "Dry Ohh",
    keyTrigger: "S",
    keyCode: 83,
    url: "https://s3.amazonaws.com/freecodecamp/drums/Dry_Ohh.mp3",
  },
  {
    id: "D",
    name: "Heater-1",
    keyTrigger: "D",
    keyCode: 68,
    url: "https://s3.amazonaws.com/freecodecamp/drums/Bld_H1.mp3",
  },
  {
    id: "Z",
    name: "Kick 1",
    keyTrigger: "Z",
    keyCode: 90,
    url: "https://s3.amazonaws.com/freecodecamp/drums/punchy_kick_1.mp3",
  },
  {
    id: "X",
    name: "Side Stick 1",
    keyTrigger: "X",
    keyCode: 88,
    url: "https://s3.amazonaws.com/freecodecamp/drums/side_stick_1.mp3",
  },
  {
    id: "C",
    name: "Snare",
    keyTrigger: "C",
    keyCode: 67,
    url: "https://s3.amazonaws.com/freecodecamp/drums/Brk_Snr.mp3",
  },
];
